version: '3.3'

services:
  mysql-db:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: row-match
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  row-match-service:
    image: row-match-service
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      TZ: UTC
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/row-match?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
